In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

import warnings 
warnings.filterwarnings("ignore")

In [4]:
from sklearn.datasets import make_classification

In [7]:
x , y = make_classification(n_samples=1000,n_features=10,n_redundant=5,n_informative=5,n_classes=2,random_state=1)   # features made  from useful features 

In [9]:
x 

array([[ 2.56999479, -0.13019997,  3.16075093, ..., -1.93094078,
         3.26130366,  2.05692145],
       [ 0.34129317,  2.51321418, -0.80416572, ...,  6.24734437,
        -1.92769365,  2.9503149 ],
       [ 2.27539972,  3.36561455,  0.17164362, ...,  2.74693781,
         0.13492444,  2.00339547],
       ...,
       [ 0.5234359 ,  1.90466429,  0.93243365, ...,  1.53945231,
         1.90646166,  1.99458587],
       [ 1.33747921,  3.25859684,  0.78792366, ...,  5.18788314,
        -0.82071083,  3.51411431],
       [-0.98534299,  0.83919047,  2.5820803 , ...,  3.04705685,
         0.66885641,  3.32838496]])

In [18]:
y

array([1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,

In [19]:
from sklearn.model_selection import train_test_split

In [21]:
x_train , x_test , y_train , y_test = train_test_split(x,y,random_state=1)

In [13]:
from sklearn.linear_model import LogisticRegression 

In [15]:
log = LogisticRegression()

In [22]:
log

LogisticRegression()

In [23]:
log.fit(x_train , y_train)

LogisticRegression()

In [26]:
y_pred = log.predict(x_test)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

In [30]:
confusion_matrix(y_test,y_pred)

array([[105,  11],
       [ 30, 104]])

In [32]:
accuracy_score(y_test,y_pred)

0.836

In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.91      0.84       116
           1       0.90      0.78      0.84       134

    accuracy                           0.84       250
   macro avg       0.84      0.84      0.84       250
weighted avg       0.85      0.84      0.84       250



In [38]:
from sklearn.metrics import roc_curve , auc

In [ ]:
log.predict_proba(x_test)[:,1]  # probabilty of one class 

array([0.98243335, 0.15805106, 0.28876845, 0.13876116, 0.5613311 ,
       0.09355495, 0.961272  , 0.31408065, 0.12214725, 0.96074986,
       0.07546863, 0.41852177, 0.71984922, 0.2396681 , 0.58087183,
       0.67319046, 0.9558778 , 0.86400861, 0.97335795, 0.07189166,
       0.44737291, 0.96033455, 0.81102071, 0.10174495, 0.91630423,
       0.54464156, 0.15353049, 0.46558558, 0.47118923, 0.16368836,
       0.24058   , 0.7705017 , 0.09309406, 0.64294778, 0.95889767,
       0.97979065, 0.98955031, 0.05130765, 0.0326951 , 0.47504985,
       0.07800903, 0.36731048, 0.01925811, 0.42730088, 0.28664126,
       0.17454997, 0.11130632, 0.35941405, 0.29377187, 0.04760137,
       0.12844691, 0.04254304, 0.64635666, 0.98359011, 0.59788093,
       0.1034639 , 0.0746215 , 0.16909565, 0.98590375, 0.97147227,
       0.99594453, 0.90684498, 0.88318077, 0.34797958, 0.94463365,
       0.19496884, 0.05754593, 0.102921  , 0.49068214, 0.72255383,
       0.24746232, 0.02045339, 0.90720294, 0.54363164, 0.98646