In [226]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

import warnings 
warnings.filterwarnings("ignore")

In [227]:
from sklearn.datasets import make_classification 

In [228]:
x,y = make_classification(n_samples=1000,n_features=10,n_classes=3,n_redundant=5,n_informative=5,random_state=1)

In [229]:
x

array([[ 1.89149379, -0.39847585,  1.63856893, ...,  0.58810926,
        -0.02542177, -0.52835426],
       [ 1.86913773, -0.56336215,  2.03411807, ..., -0.55633   ,
        -0.27340013,  0.72129251],
       [ 1.95259701, -2.83144572,  0.19055535, ..., -0.60957741,
        -2.07750191, -1.75469982],
       ...,
       [ 1.98033054,  1.37228804,  1.67376262, ...,  2.75687956,
        -0.20719842,  0.39299534],
       [-1.54305631, -0.27530218,  0.38744703, ...,  0.72769107,
         0.51983329, -1.92306657],
       [ 1.17970389, -3.3812155 , -0.1498426 , ...,  1.24640268,
        -4.00356845, -3.01027048]])

In [230]:
from sklearn.linear_model import LogisticRegression

In [231]:
# ovr (one versus rest)

In [232]:
from sklearn.model_selection import train_test_split

In [233]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.30,random_state=1)

In [234]:
model = LogisticRegression(multi_class="ovr",solver="lbfgs")

In [235]:
model

LogisticRegression(multi_class='ovr')

In [236]:
model.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [237]:
y_pred = model.predict(x_test)

In [238]:
from sklearn.metrics import confusion_matrix , accuracy_score

In [239]:
confusion_matrix(y_test , y_pred)

array([[75, 21,  3],
       [10, 58, 21],
       [23, 14, 75]])

In [240]:
accuracy_score(y_test , y_pred)

0.6933333333333334

In [241]:
 # one more implementation 

In [242]:
from sklearn.datasets import load_iris

In [243]:
data = load_iris()

In [244]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [245]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [246]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [247]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [248]:
df["target"] = data.target

In [249]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [250]:
x1 = df.iloc[:,:-1]

In [251]:
y1 = df.iloc[:,-1]

In [252]:
from sklearn.model_selection import train_test_split

In [253]:
x1_train , x1_test , y1_train , y1_test = train_test_split(x1,y1,test_size=0.30,random_state=1)

In [254]:
model2 = LogisticRegression(max_iter=300)   # we are not passing anything by default it will dectect it is multiclass classification

In [255]:
model2

LogisticRegression(max_iter=300)

In [256]:
model2.fit(x1_train,y1_train)

LogisticRegression(max_iter=300)

In [257]:
y_pred = model2.predict(x1_test)

In [258]:
confusion_matrix(y1_test,y_pred)

array([[14,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 13]])

In [259]:
accuracy_score(y1_test,y_pred)

0.9777777777777777

In [260]:
model2.predict_proba(x1_test) # tools is roc curves 

array([[9.85025380e-01, 1.49745357e-02, 8.47915830e-08],
       [2.73870325e-01, 7.22403384e-01, 3.72629055e-03],
       [6.87873269e-03, 8.67910215e-01, 1.25211053e-01],
       [9.85580983e-01, 1.44187914e-02, 2.25309517e-07],
       [1.61762696e-06, 1.99353129e-02, 9.80063070e-01],
       [4.82076816e-03, 5.87872567e-01, 4.07306665e-01],
       [1.74155232e-04, 1.29200372e-01, 8.70625473e-01],
       [9.58218377e-01, 4.17780979e-02, 3.52555249e-06],
       [9.68302350e-01, 3.16968084e-02, 8.41649093e-07],
       [1.34382832e-05, 3.10695058e-02, 9.68917056e-01],
       [1.98946645e-02, 8.69216957e-01, 1.10888378e-01],
       [9.67083170e-01, 3.29154312e-02, 1.39859077e-06],
       [7.00812405e-06, 3.82224111e-02, 9.61770581e-01],
       [7.71310187e-03, 7.66892521e-01, 2.25394377e-01],
       [7.47574432e-03, 7.31252618e-01, 2.61271638e-01],
       [9.87344795e-01, 1.26550076e-02, 1.97259900e-07],
       [2.35786558e-02, 9.29632499e-01, 4.67888452e-02],
       [1.15650048e-02, 6.62101

In [261]:
# predict_proba will obtain the probability that given data point belongs to each class 

In [262]:
# on the other hand the predict will analyze the most likely class will be 