In [106]:
import pandas as pd
import numpy as np 
import matplotlib as plt 
import seaborn as sns 



import warnings
warnings.filterwarnings("ignore")

In [107]:
from sklearn.datasets import fetch_california_housing

In [108]:
data = fetch_california_housing()
print(data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per ce

In [109]:
data.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [110]:
data.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [111]:
# problem statement --> predict the median house value for california district

In [112]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [113]:
df["target_price"] = data.target

In [114]:
df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target_price
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010


In [115]:
# split x and y
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [116]:
# train test split 
from sklearn.model_selection import train_test_split


x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.20,random_state=1)

In [117]:
from sklearn.linear_model import LinearRegression

In [118]:
lr = LinearRegression()

In [119]:
lr

LinearRegression()

In [120]:
lr.fit(x_train,y_train)

LinearRegression()

In [121]:
lr.coef_

array([ 4.38565392e-01,  9.68722037e-03, -1.04705005e-01,  6.32189474e-01,
       -3.67690711e-06, -3.44771323e-03, -4.25964056e-01, -4.40601114e-01])

In [122]:
lr.intercept_

np.float64(-37.51575415983673)

In [123]:
y_pred = lr.predict(x_test)

In [124]:
y_pred

array([2.12567705, 0.93977118, 2.70887192, ..., 2.9460839 , 2.63875476,
       1.46985176])

In [125]:
from sklearn.metrics import r2_score

In [126]:
r2_score(y_test,y_pred)

0.596596837481235

In [132]:
lr

LinearRegression()

In [133]:
import pickle

In [ ]:
pickle.dump(lr,open("modl.pkl","wb"))  # we can also done this with job lib

In [135]:
import joblib