In [2]:
import numpy as np

In [3]:
# create numpy array 
# with random values 
np.random.rand(2,4)  # 4 values and 2 array 

array([[0.63747154, 0.45895283, 0.17211914, 0.03797337],
       [0.70701907, 0.80828031, 0.72825177, 0.12763488]])

In [ ]:
# with numerical values 
# 1 --> step based 
np.arange(1,5)   # start stop and step   it will only give interger values 
# 2 --> count based ranges 
np.linspace(1,5) # it also give float values 

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [6]:
# how to perform element wise operations on numpy
a = 2 
b = 5
np.add(a,b)
np.subtract(a,b)
np.divide(a,b)
np.power(b,2)




np.int64(25)

In [17]:
# to select a specific subset of elements from numpy array

arr = np.array([[1,2,3],[2,3,45],[1,2,3]])
  # to select a specific we use indexing and slecing
arr[-1]


array([1, 2, 3])

In [27]:
# aggeration function
data = np.array([1,2,3,4,5,6,7,8,9])
np.sum(data)
np.mean(data)
np.var(data)
np.std(data)
np.min(data)
np.max(data)

np.int64(9)

In [41]:
# how we handle missing values 
data = np.array([1,2,np.nan,4,5,6,np.nan,8,9])  # --> detect missing values 
np.isnan(data).sum()

#remove missing values 
data[~np.isnan(data)]  # negation false means do not give nan value give other 

# replace the missing values 

np.where(np.isnan(data),0,data)  

# interpolation



array([1., 2., 0., 4., 5., 6., 0., 8., 9.])